[package]
name = "dicom_file_walker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.4"
tokio = { version = "1.10.0", features = ["full"] }
walkdir = "2.3.2"
